---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.j5t.io
  resources:
  - secretservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.j5t.io
  resources:
  - secretservices/finalizers
  verbs:
  - update
- apiGroups:
  - apps.j5t.io
  resources:
  - secretservices/status
  verbs:
  - get
  - patch
  - update
