# permissions for end users to view secretservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretservice-viewer-role
rules:
- apiGroups:
  - apps.j5t.io.j5t.io
  resources:
  - secretservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.j5t.io.j5t.io
  resources:
  - secretservices/status
  verbs:
  - get
