apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "secret-service-operator.labels" . | nindent 4 }}
  name: {{ include "secret-service-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "secret-service-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
