apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secret-service-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:    
    app.kubernetes.io/component: "controller"
    {{- include "secret-service-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
