name: Release Helm charts

on:
  push:
    branches:
      - "main"
    paths:
      - "deploy/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up Helm
        uses: Azure/setup-helm@v4

      - name: Package Helm chart
        id: helm_package
        run: |
          helm package deploy/charts/secret-service-operator -d .cr-release-packages
          PKG_NAME=$(ls .cr-release-packages/*.tgz)
          echo "name=$PKG_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-service-operator
          path: |
            ${{ steps.helm_package.outputs.name }}
    
      - name: Release Helm chart
        env:
          CR_GENERATE_RELEASE_NOTES: true
          CR_MAKE_RELEASE_LATEST: true
          CR_SKIP_EXISTING: true
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: helm/chart-releaser-action@v1
        with:
          skip_packaging: true